<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://xmlns.oracle.com/ns/order" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/POProcesing/POProcessing/approveLargeOrder"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/POProcesing/POProcessing/WriteApprovalResults"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/approveLargeOrder.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Order" namespace="http://xmlns.oracle.com/ns/order"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WriteApprovalResults.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Order" namespace="http://xmlns.oracle.com/ns/order"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SAT OCT 31 11:49:20 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:Order>
         <ns0:customerId>
            <xsl:value-of select="/ns0:Order/ns0:customerId"/>
         </ns0:customerId>
         <ns0:orderId>
            <xsl:value-of select="/ns0:Order/ns0:orderId"/>
         </ns0:orderId>
         <ns0:prodName>
            <xsl:value-of select="/ns0:Order/ns0:prodName"/>
         </ns0:prodName>
         <ns0:itemType>
            <xsl:value-of select="/ns0:Order/ns0:itemType"/>
         </ns0:itemType>
         <ns0:price>
            <xsl:value-of select="/ns0:Order/ns0:price"/>
         </ns0:price>
         <ns0:qty>
            <xsl:value-of select="/ns0:Order/ns0:qty"/>
         </ns0:qty>
         <ns0:status>
            <xsl:value-of select="/ns0:Order/ns0:status"/>
         </ns0:status>
         <ns0:creditCardInfo>
            <ns0:cardNumber>
               <xsl:value-of select="/ns0:Order/ns0:creditCardInfo/ns0:cardNumber"/>
            </ns0:cardNumber>
            <ns0:cardType>
               <xsl:value-of select="/ns0:Order/ns0:creditCardInfo/ns0:cardType"/>
            </ns0:cardType>
         </ns0:creditCardInfo>
      </ns0:Order>
   </xsl:template>
</xsl:stylesheet>
